# Generated by Django 5.2.9 on 2026-01-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=250)),
                ('name', models.TextField(max_length=250)),
                ('size', models.IntegerField()),
                ('content_type', models.TextField(max_length=12)),
                ('r2_key', models.TextField(max_length=250)),
                ('hash_md5', models.TextField(max_length=32)),
                ('num_pages', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('page', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='users.user')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.document')),
            ],
        ),
    ]
