# Generated by Django 5.2.9 on 2025-12-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='block',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='users.user'),
        ),
    ]
