# Generated by Django 5.2.9 on 2025-12-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_block_page_alter_block_document_alter_block_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='user_id',
        ),
    ]
