# Generated by Django 5.2.9 on 2025-12-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rename_document_block_document_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
