# Generated by Django 5.2.9 on 2025-12-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='document',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='exam',
            new_name='exam_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='opciones',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='enunciado',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explicacion',
        ),
        migrations.RemoveField(
            model_name='question',
            name='respuesta_correcta',
        ),
    ]
