# Generated by Django 5.2.9 on 2025-12-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_document_exam_document_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='user_id',
            new_name='user',
        ),
    ]
