# Generated by Django 5.2.9 on 2026-01-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_create_examattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examattempt',
            new_name='exams_exama_user_id_df4f06_idx',
            old_name='exams_exama_user_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='examattempt',
            new_name='exams_exama_exam_id_c00966_idx',
            old_name='exams_exama_exam_id_idx',
        ),
    ]
